kind: Template
apiVersion: v1
metadata:
  annotations:
    description: Build template for a schema-spy server.
    tags: schema-spy
  name: ${NAME}-build-template
objects:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: ${NAME}
      labels:
        name: ${NAME}
        app: ${APP_NAME}${SUFFIX}
        app-group: ${APP_GROUP}
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: ${NAME}
      labels:
        name: ${NAME}
        app: ${APP_NAME}${SUFFIX}
        app-group: ${APP_GROUP}
    spec:
      source:
        type: Git
        git:
          uri: ${GIT_REPO_URL}
          ref: ${GIT_REF}
        contextDir: ${SOURCE_CONTEXT_DIR}
      strategy:
        type: Docker
        dockerStrategy:
          from:
            kind: DockerImage
            name: "${DOCKER_IMAGE_REGISTRY}${SOURCE_IMAGE_NAME}"
          pullSecret:
            name: ${DOCKER_PULL_CREDENTIALS}
      output:
        to:
          kind: ImageStreamTag
          name: ${NAME}:${OUTPUT_IMAGE_TAG}
      triggers:
        - type: ConfigChange
        - type: ImageChange
parameters:
  - name: NAME
    displayName: Schema Spy Name
    description: The name assigned to all of the schema spy objects defined in this template.
    required: true
    value: schema-spy
  - name: SUFFIX
    displayName: Suffix
    description: A name suffix used for all objects
    required: false
    value: -bc
  - name: APP_NAME
    displayName: App Name
    description: Used to group components together in the OpenShift console.
    required: true
    value: orgbook
  - name: APP_GROUP
    displayName: App Group
    description: The name assigned to all of the deployments in this project.
    required: true
    value: aries-vcr
  - name: GIT_REPO_URL
    displayName: Git Repo URL
    description: The URL to the schema spy implementation.
    required: true
    value: https://github.com/bcgov/SchemaSpy.git
  - name: GIT_REF
    displayName: Git Reference
    description: The git reference or branch.
    required: true
    value: master
  - name: SOURCE_CONTEXT_DIR
    displayName: Source Context Directory
    description: The source context directory.
    required: false
    value: ""
  - name: DOCKER_IMAGE_REGISTRY
    displayName: Docker Image Registry
    description: The name of the Docker image registry.
    required: false
    value: docker-remote.artifacts.developer.gov.bc.ca/
  - name: SOURCE_IMAGE_NAME
    displayName: Source Image Name
    description: The name of the Docker image to be used for the build. Overrides the FROM instruction in the Dockerfile.
    required: false
    value: openjdk:jre-alpine
  - name: DOCKER_PULL_CREDENTIALS
    displayName: Docker Pull Credentials
    description: The name of the secret that will be used to authenticate with the Docker image registry.
    required: false
    value: docker-pull-secret
  - name: OUTPUT_IMAGE_TAG
    displayName: Output Image Tag
    description: The tag given to the built image.
    required: true
    value: latest
