kind: Template
apiVersion: v1
metadata:
  name: ${NAME}-build-template
objects:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: ${NAME}
      labels:
        name: ${NAME}
        app: ${APP_NAME}${SUFFIX}
        app-group: ${APP_GROUP}
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: ${NAME}
      labels:
        name: ${NAME}
        app: ${APP_NAME}${SUFFIX}
        app-group: ${APP_GROUP}
    spec:
      triggers:
        - type: ConfigChange
      runPolicy: Serial
      source:
        type: Git
        contextDir: ${SOURCE_CONTEXT_DIR}
        git:
          uri: ${GIT_REPO_URL}
          ref: ${GIT_REF}
      strategy:
        type: Source
        sourceStrategy:
          from:
            kind: ${SOURCE_IMAGE_KIND}
            name: ${SOURCE_IMAGE_NAME}:${SOURCE_IMAGE_TAG}
          env:
            - name: THEME
              value: ${THEME}
      output:
        to:
          kind: ImageStreamTag
          name: ${NAME}:${OUTPUT_IMAGE_TAG}
      resources:
        requests:
          cpu: ${CPU_REQUEST}
          memory: ${MEMORY_REQUEST}
        limits:
          cpu: ${CPU_LIMIT}
          memory: ${MEMORY_LIMIT}
parameters:
  - name: NAME
    displayName: Name
    description: The name assigned to all of the objects defined in this template.
    required: true
    value: frontend-artifacts
  - name: SUFFIX
    displayName: Suffix
    description: A name suffix used for all objects
    required: false
    value: -bc
  - name: APP_NAME
    displayName: App Name
    description: Used to group components together in the OpenShift console.
    required: true
    value: orgbook
  - name: APP_GROUP
    displayName: App Group
    description: The name assigned to all of the deployments in this project.
    required: true
    value: aries-vcr
  - name: OUTPUT_IMAGE_TAG
    displayName: Output Image Tag
    description: The tag given to the built image.
    required: true
    value: latest
  - name: GIT_REPO_URL
    displayName: GIT Source Repo URL
    description: A GIT URL to your source code.
    required: true
    value: https://github.com/bcgov/aries-vcr.git
  - name: GIT_REF
    displayName: Git Reference
    description: The git reference or branch.
    required: true
    value: master
  - name: SOURCE_CONTEXT_DIR
    displayName: Source Context Directory
    description: The source context directory.
    required: false
    value: client
  - name: SOURCE_IMAGE_KIND
    displayName: Source Image Kind
    required: true
    description: The 'kind' (type) of the  source image; typically ImageStreamTag, or DockerImage.
    value: DockerImage
  - name: SOURCE_IMAGE_NAME
    displayName: Source Image Name
    description: The name of the source image.
    required: true
    value: registry.redhat.io/ubi8/nodejs-12
  - name: SOURCE_IMAGE_TAG
    displayName: Source Image Tag
    description: The tag of the source image.
    required: true
    value: latest
  - name: THEME
    displayName: The aries-vcr Theme Name
    description: The name of the theme to be used for the site.
    value: default
  - name: CPU_LIMIT
    displayName: Resources CPU Limit
    description: The resources CPU limit (in cores) for this build.
    required: true
    value: "1"
  - name: MEMORY_LIMIT
    displayName: Resources Memory Limit
    description: The resources Memory limit (in Mi, Gi, etc) for this build.
    required: true
    value: 4Gi
  - name: CPU_REQUEST
    displayName: Resources CPU Request
    description: The resources CPU request (in cores) for this build.
    required: true
    value: 250m
  - name: MEMORY_REQUEST
    displayName: Resources Memory Request
    description: The resources Memory request (in Mi, Gi, etc) for this build.
    required: true
    value: 2Gi
